apiVersion: apps/v1
kind: Deployment
metadata:
  name: auditchecklistmodule-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AuditChecklistModule
  template:
    metadata:
      labels:
        app: AuditChecklistModule
    spec:
      containers:
      - name: dockerrepos
        image: arpan848863acr.azurecr.io/dockerrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfig

---
apiVersion: v1
kind: Service
metadata:
  name: auditchecklistmodule
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: AuditChecklistModule

